CREATE DATABASE web_day9;
USE web_day9;


CREATE TABLE PASSPORT(
	ID INT NOT NULL AUTO_INCREMENT, 
    NUMBER VARCHAR(50) NOT NULL, 
    PRIMARY KEY ( ID )
);

CREATE TABLE STUDENT(
	ID INT NOT NULL AUTO_INCREMENT, 
    NAME VARCHAR(50) NOT NULL, 
    PASSPORT_ID INT NOT NULL,
    PRIMARY KEY ( ID ),
    FOREIGN KEY (PASSPORT_ID) REFERENCES PASSPORT (ID)
);

insert into PASSPORT(NUMBER) values ('000A001'), ('000A002');

insert into STUDENT(NAME, PASSPORT_ID) values ('huy tran quang', 1), ('xuyen bui thi kim', 2);
